"""
Django settings for graveyard project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
import dotenv

dotenv.load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-02c+j)k@z3d$zp5&opmk!1r$#ya(cmf284_@^65d1ge*dc^s^!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# In development (DEBUG=True), Django allows all hosts by default
# For production, set ALLOWED_HOSTS in .env to specific domains (comma-separated)
# Example: ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
allowed_hosts_str = config('ALLOWED_HOSTS', default='')
if allowed_hosts_str:
    ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_str.split(',') if h.strip()]
else:
    # Default to localhost only - MUST set ALLOWED_HOSTS in .env for production
    # This prevents host header injection attacks
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
AUTH_USER_MODEL = 'users.User'


# Application definition

INSTALLED_APPS = [
    'daphne', # Must be at the top
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS support for frontend
    'ai_endpoints',
    'bot',
    'departments',
    'message_app',
    'users',
    'support_tools',
    'broadcast',
    'websockets',
    'api',
    'rest_framework',
    'rest_framework_simplejwt',
    'channels',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django Channels
ASGI_APPLICATION = 'graveyard.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [(config('REDIS_HOST', default='127.0.0.1'), config('REDIS_PORT', default=6379, cast=int))],
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'graveyard.security_middleware.SecurityMiddleware',  # Custom security middleware (blocks suspicious requests)
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be early)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Configuration for Frontend
# Allow CORS from environment variable (comma-separated list) or default to localhost
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://narpaymurojaat.uz',
    cast=lambda v: [origin.strip() for origin in v.split(',')]
)

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'graveyard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'graveyard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'graveyard.db_backend',  # Custom backend with automatic reconnection
        'NAME': os.getenv('DB_NAME', 'gov_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            # Set MySQL timeouts to match Django's connection management
            # wait_timeout and interactive_timeout are set to 8 hours (28800 seconds)
            # This matches MySQL's default and prevents premature connection closure
            'init_command': (
                "SET sql_mode='STRICT_TRANS_TABLES', "
                "wait_timeout=31536000, "
                "interactive_timeout=31536000"
            ),
            'connect_timeout': 10,  # Time to wait for initial connection
            'read_timeout': 30,  # Time to wait for read operations
            'write_timeout': 30,  # Time to wait for write operations
            'charset': 'utf8mb4',
            'autocommit': True,  # Enable autocommit for better connection handling
        },
        # Connection pooling settings
        # CONN_MAX_AGE: How long to keep connections open (in seconds)
        # Set to 300 seconds (5 minutes) - less than wait_timeout but long enough for performance
        # The custom db_backend automatically handles reconnection on connection errors
        'CONN_MAX_AGE': 300,  # Reuse connections for 5 minutes (balance between performance and reliability)
        'CONN_HEALTH_CHECKS': True,  # Check connection health before reusing (closes stale connections)
        'ATOMIC_REQUESTS': False,  # Keep False for better performance
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



CSRF_TRUSTED_ORIGINS = [
   "https://blowzily-glossological-geraldine.ngrok-free.dev"
]

# When running behind ngrok (or another reverse proxy that terminates TLS),
# trust the X-Forwarded-Proto header so Django knows the original scheme was HTTPS.
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Security Settings - Production Hardening
if not DEBUG:
    # HTTPS Security (only in production)
    SECURE_SSL_REDIRECT = False  # Set to True if using HTTPS directly (not behind proxy)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATIC_ROOT = BASE_DIR / "staticfiles"



# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

GEMINI_API_KEY = config('GEMINI_API_KEY')
TOKEN_BOT = config('TOKEN_BOT')
TELEGRAM_BOT_TOKEN = TOKEN_BOT

TELEGRAM_FILE_CACHE_DIR = config('TELEGRAM_FILE_CACHE_DIR', default='telegram_files')

MEDIA_ROOT = os.path.join(BASE_DIR, "media")
MEDIA_URL = '/media/'
THUMBNAIL_CACHE_DIR = config('THUMBNAIL_CACHE_DIR', default='thumbnails')
THUMBNAIL_MAX_SIZE = (512, 512)  # px, max thumbnail dimension
AI_MICROSERVICE_URL = config('AI_MICROSERVICE_URL', default='http://localhost:8001/api/v1')

# SLA Configuration
SLA_THRESHOLD_DAYS = config('SLA_THRESHOLD_DAYS', default=3, cast=int)
HOLD_EXTENSION_DAYS = config('HOLD_EXTENSION_DAYS', default=1, cast=int)

# Celery Configuration
# Use REDIS_HOST and REDIS_PORT from environment or defaults
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'redis://{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'redis://{REDIS_HOST}:{REDIS_PORT}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Celery Beat Schedule (can also be defined in celery.py)
# The schedule is defined in celery.py for better organization

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'security': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'security_file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'security.log',
            'formatter': 'security',
        },
    },
    'loggers': {
        'security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'security_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}