# Generated by Django 5.2.9 on 2025-12-05 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('message_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_staff_message', models.BooleanField(default=False)),
                ('sender_platform', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('system', 'System Auto-Message')], default='web', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('quarantined', models.BooleanField(default=False)),
                ('quarantined_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('voice', 'Voice'), ('sticker', 'Sticker')], default='text', max_length=32)),
                ('text', models.TextField(blank=True, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='message_media/%Y/%m/%d/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('telegram_file_id', models.CharField(blank=True, max_length=256, null=True)),
                ('media_group_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
