# Generated by Django 5.2.9 on 2025-12-05 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
    ]
