# Generated by Django 5.2.9 on 2025-12-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_remove_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_uz',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
