# Generated by Django 5.2.9 on 2025-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_uz', models.CharField(db_index=True, max_length=128)),
                ('name_ru', models.CharField(blank=True, max_length=128, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Neighborhood',
                'verbose_name_plural': 'Neighborhoods',
                'ordering': ['name_uz'],
                'indexes': [models.Index(fields=['name_uz'], name='support_too_name_uz_cac152_idx')],
            },
        ),
    ]
