# Generated by Django 5.2.9 on 2025-12-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('intent_label', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('suggested_department_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('suggested_department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('reasoning_text', models.TextField(blank=True, null=True)),
                ('vector_search_results', models.JSONField(blank=True, null=True)),
                ('is_corrected', models.BooleanField(db_index=True, default=False)),
                ('corrected_department_id', models.BigIntegerField(blank=True, null=True)),
                ('correction_notes', models.TextField(blank=True, null=True)),
                ('prompt_tokens', models.IntegerField(blank=True, null=True)),
                ('completion_tokens', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Analysis Log',
                'verbose_name_plural': 'AI Analysis Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InjectionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_injection', models.BooleanField(db_index=True, default=False)),
                ('risk_score', models.FloatField(help_text='0.0 to 1.0 safety score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
