# Generated by Django 5.2.9 on 2025-12-05 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_endpoints', '0001_initial'),
        ('message_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='corrected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='message',
            field=models.ForeignKey(db_column='message_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='message_app.message', to_field='message_uuid'),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='session',
            field=models.ForeignKey(db_column='session_uuid', on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to='message_app.session', to_field='session_uuid'),
        ),
        migrations.AddField(
            model_name='injectionlog',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injection_logs', to='message_app.message'),
        ),
    ]
